$terms = @(
  "男鞋","女鞋","童鞋","男童鞋","女童鞋","婴儿鞋","小童鞋","中童鞋","大童鞋",
  "运动鞋","男运动鞋","女运动鞋","童运动鞋",
  "跑步鞋","男跑步鞋","女跑步鞋","儿童跑步鞋","缓震跑步鞋","竞速跑步鞋","马拉松鞋",
  "训练鞋","男训练鞋","女训练鞋",
  "健走鞋","男健走鞋","女健走鞋",
  "越野跑鞋","男越野跑鞋","女越野跑鞋",
  "篮球鞋","男篮球鞋","女篮球鞋","儿童篮球鞋","高帮篮球鞋","低帮篮球鞋",
  "足球鞋","男足球鞋","女足球鞋","儿童足球鞋","碎钉足球鞋","长钉足球鞋","室内足球鞋",
  "排球鞋","男排球鞋","女排球鞋",
  "羽毛球鞋","男羽毛球鞋","女羽毛球鞋",
  "网球鞋","男网球鞋","女网球鞋",
  "乒乓球鞋","男乒乓球鞋","女乒乓球鞋",
  "滑板鞋","男滑板鞋","女滑板鞋",
  "板鞋","男板鞋","女板鞋","儿童板鞋",
  "帆布鞋","男帆布鞋","女帆布鞋","儿童帆布鞋","高帮帆布鞋","低帮帆布鞋",
  "休闲鞋","男休闲鞋","女休闲鞋","儿童休闲鞋",
  "小白鞋","男小白鞋","女小白鞋","儿童小白鞋",
  "乐福鞋","男乐福鞋","女乐福鞋",
  "豆豆鞋","男豆豆鞋","女豆豆鞋",
  "船鞋","男船鞋","女船鞋",
  "驾车鞋","男驾车鞋","女驾车鞋",
  "牛津鞋","男牛津鞋","女牛津鞋",
  "德比鞋","男德比鞋","女德比鞋",
  "布洛克鞋","男布洛克鞋","女布洛克鞋",
  "孟克鞋","男孟克鞋","女孟克鞋",
  "正装鞋","男正装鞋","女正装鞋",
  "商务皮鞋","男商务皮鞋","女商务皮鞋",
  "高跟鞋","细跟高跟鞋","粗跟高跟鞋","猫跟鞋","坡跟鞋","厚底鞋","松糕鞋",
  "玛丽珍鞋","女玛丽珍鞋",
  "浅口单鞋","女浅口单鞋",
  "尖头单鞋","圆头单鞋","方头单鞋",
  "芭蕾舞鞋","女芭蕾舞鞋",
  "平底单鞋","女平底单鞋",
  "凉鞋","男凉鞋","女凉鞋","儿童凉鞋","沙滩凉鞋","运动凉鞋","女童凉鞋","男童凉鞋","罗马凉鞋","女罗马凉鞋","夹趾凉鞋","一字带凉鞋","厚底凉鞋","高跟凉鞋","坡跟凉鞋",
  "沙滩鞋","男沙滩鞋","女沙滩鞋","儿童沙滩鞋",
  "洞洞鞋","男洞洞鞋","女洞洞鞋","儿童洞洞鞋",
  "拖鞋","男拖鞋","女拖鞋","儿童拖鞋",
  "人字拖","男款人字拖","女款人字拖",
  "运动拖鞋","男运动拖鞋","女运动拖鞋",
  "居家拖鞋","浴室拖鞋","户外拖鞋","冬拖鞋",
  "棉拖鞋","男棉拖鞋","女棉拖鞋","儿童棉拖鞋",
  "短靴","男短靴","女短靴","儿童短靴",
  "切尔西靴","男切尔西靴","女切尔西靴",
  "马丁靴","男马丁靴","女马丁靴","儿童马丁靴",
  "工装靴","男工装靴","女工装靴",
  "沙漠靴","男沙漠靴","女沙漠靴",
  "雪地靴","男雪地靴","女雪地靴","儿童雪地靴","UGG雪地靴",
  "登山鞋","男登山鞋","女登山鞋","儿童登山鞋",
  "徒步鞋","男徒步鞋","女徒步鞋","儿童徒步鞋",
  "雨鞋","男雨鞋","女雨鞋","儿童雨鞋",
  "胶鞋","儿童胶鞋",
  "劳保鞋","男劳保鞋","女劳保鞋",
  "安全鞋","男安全鞋",
  "厨房鞋",
  "护士鞋","女护士鞋",
  "医生鞋",
  "舞蹈鞋","女舞蹈鞋","儿童舞蹈鞋","拉丁舞鞋","芭蕾软鞋","爵士舞鞋",
  "体操鞋","儿童体操鞋",
  "轮滑鞋","儿童轮滑鞋","成人轮滑鞋","直排轮滑鞋",
  "溜冰鞋","儿童溜冰鞋",
  "室内鞋","幼儿园室内鞋","小学室内鞋",
  "手工布鞋","老北京布鞋","男布鞋","女布鞋",
  "妈妈鞋","爸爸鞋","奶奶鞋","爷爷鞋",
  "老人健步鞋","老人运动鞋","老人皮鞋","老人棉鞋","老人凉鞋","老人拖鞋",
  "工作鞋女","工作鞋男",
  "防静电鞋","厨师鞋",
  "Nike男鞋","Nike女鞋","Nike童鞋","Nike跑步鞋","Nike篮球鞋","Nike Air Max系列","Nike Air Max 90","Nike Air Max 97","Nike Air Max 270","Nike Air Force 1","Nike Air Force 1男","Nike Air Force 1女","Nike Air Force 1童","Nike Dunk","Nike Dunk男","Nike Dunk女","Nike Dunk童","Nike Dunk Low","Nike Dunk High","Nike Jordan系列","Nike乔丹鞋","Jordan男鞋","Jordan女鞋","Jordan童鞋","Air Jordan 1","Air Jordan 1男","Air Jordan 1女","Air Jordan 1童","Air Jordan 3","Air Jordan 4","Air Jordan 11","Nike Blazer","Nike Cortez","Nike Vapormax","Nike React","Nike Pegasus","Nike Metcon","Nike Free","Nike Zoom","Nike Kyrie","Nike LeBron","Nike Kobe","Nike GT Cut","Nike初代",
  "Adidas男鞋","Adidas女鞋","Adidas童鞋","Adidas跑步鞋","Adidas篮球鞋","Adidas足球鞋","Adidas三叶草","Adidas Originals","Adidas Yeezy","Yeezy男","Yeezy女","Yeezy童","Yeezy 350","Yeezy 500","Yeezy 700","Adidas Ultraboost","Adidas Ultraboost男","Adidas Ultraboost女","Adidas NMD","Adidas NMD男","Adidas NMD女","Adidas Superstar","Adidas Superstar男","Adidas Superstar女","Adidas Superstar童","Adidas Stan Smith","Adidas Stan Smith男","Adidas Stan Smith女","Adidas Campus","Adidas Forum","Adidas Ozweego","Adidas Pureboost","Adidas Solarboost","Adidas Adizero","Adidas Predator足球鞋","Adidas Copa足球鞋","Adidas Harden篮球鞋","Adidas D Rose篮球鞋","Adidas Dame篮球鞋","Adidas四叶草",
  "New Balance男鞋","New Balance女鞋","New Balance童鞋","New Balance 574","New Balance 574男","New Balance 574女","New Balance 574童","New Balance 327","New Balance 327男","New Balance 327女","New Balance 2002R","New Balance 990","New Balance 992","New Balance 993","New Balance 996","New Balance 997","New Balance 998","New Balance 580","New Balance 373","New Balance 530","New Balance 608","New Balance 247","New Balance Hierro","New Balance Fresh Foam","New Balance FuelCell","New Balance复古鞋",
  "Asics男鞋","Asics女鞋","Asics童鞋","Asics跑步鞋","Asics Gel-Kayano","Asics Gel-Nimbus","Asics Gel-Cumulus","Asics Gel-Quantum","Asics GT-2000","Asics GT-1000","Asics Magic Speed","Asics Novablast","Asics Gel-Kinsei","Asics Gel-Lyte III","Asics Gel-Lyte V","Asics Gel-1130","Asics Gel-1090","Asics Gel-Venture","Asics排球鞋","Asics网球鞋","Asics摔跤鞋","Asics虎走","Asics亚瑟士",
  "Skechers男鞋","Skechers女鞋","Skechers童鞋","Skechers健步鞋","Skechers Go Walk","Skechers Go Run","Skechers Arch Fit","Skechers D'Lites","Skechers Memory Foam","Skechers一脚蹬","Skechers跑步鞋","Skechers熊猫鞋","Skechers斯凯奇",
  "Under Armour男鞋","Under Armour女鞋","Under Armour童鞋","Under Armour跑步鞋","Under Armour篮球鞋","Under Armour训练鞋","Under Armour HOVR","Under Armour Charged","Under Armour Micro G","Under Armour Curry","Under Armour安德玛",
  "Puma男鞋","Puma女鞋","Puma童鞋","Puma跑步鞋","Puma Suede","Puma Suede男","Puma Suede女","Puma RS-X","Puma RS-X男","Puma RS-X女","Puma Future Rider","Puma Cali","Puma Smash","Puma Leadcat拖鞋","Puma彪马",
  "Reebok男鞋","Reebok女鞋","Reebok童鞋","Reebok锐步","Reebok Classic","Reebok Club C","Reebok Nano训练鞋","Reebok Floatride","Reebok Zig","Reebok Instapump","Reebok DMX",
  "Converse男鞋","Converse女鞋","Converse童鞋","Converse帆布鞋","Converse Chuck Taylor","Converse Chuck 70","Converse One Star","Converse Jack Purcell","Converse Run Star Hike","Converse匡威",
  "Vans男鞋","Vans女鞋","Vans童鞋","Vans Old Skool","Vans Old Skool男","Vans Old Skool女","Vans Sk8-Hi","Vans Sk8-Hi男","Vans Sk8-Hi女","Vans Slip-On","Vans Era","Vans Authentic","Vans UltraRange","Vans万斯",
  "李宁男鞋","李宁女鞋","李宁童鞋","李宁跑步鞋","李宁篮球鞋","李宁训练鞋","李宁羽毛球鞋","李宁超轻系列","李宁赤兔","李宁烈骏","李宁绝影","李宁飞电","李宁越影","李宁悟道","李宁韦德之道","李宁全城","李宁闪击","李宁驭帅","李宁音速","李宁空袭","李宁反伍","李宁裂变","李宁云科技","李宁䨻科技","李宁弧科技",
  "安踏男鞋","安踏女鞋","安踏童鞋","安踏跑步鞋","安踏篮球鞋","安踏训练鞋","安踏氢跑鞋","安踏创跑鞋","安踏C37","安踏C37男","安踏C37女","安踏C37童","安踏霸道","安踏霸道男","安踏霸道女","安踏霸道童","安踏KT系列","安踏克莱汤普森","安踏KT7","安踏KT8","安踏狂潮","安踏水花","安踏要疯","安踏海沃德","安踏GH系列","安踏氮科技","安踏虫洞科技","安踏儿童","安踏儿童运动鞋","安踏儿童篮球鞋","安踏儿童跑步鞋","安踏童鞋板鞋",
  "匹克男鞋","匹克女鞋","匹克童鞋","匹克跑步鞋","匹克篮球鞋","匹克态极","匹克态极男","匹克态极女","匹克态极童","匹克态极3.0","匹克态极4.0","匹克态极拖鞋","匹克态极洞洞鞋","匹克闪现","匹克闪现男","匹克闪现女","匹克大三角","匹克轻弹","匹克澎湃科技","匹克儿童态极",
  "特步男鞋","特步女鞋","特步童鞋","特步跑步鞋","特步动力巢","特步氢风科技","特步减震旋","特步160X","特步竞速","特步騛速","特步特步儿童",
  "361度男鞋","361度女鞋","361度童鞋","361度跑步鞋","361度篮球鞋","361度国际线","361度Spire系列","361度Q弹科技","361度AG系列","361度阿隆戈登","361度Big3","361度禅系列","361度儿童运动鞋","361度雨屏",
  "回力男鞋","回力女鞋","回力童鞋","回力帆布鞋","回力高帮帆布鞋","回力低帮帆布鞋","回力小白鞋","回力板鞋","回力WXY系列","回力WB系列","回力情侣鞋","回力德训鞋","回力老爹鞋","回力复古老爹鞋","回力休闲鞋","回力儿童小白鞋","回力童鞋板鞋",
  "飞跃帆布鞋","飞跃男鞋","飞跃女鞋","飞跃童鞋","飞跃田径鞋","飞跃小白鞋",
  "大博文男鞋","大博文女鞋","大博文童鞋",
  "双星男鞋","双星女鞋","双星童鞋","双星帆布鞋","双星羽毛球鞋",
  "人本帆布鞋","人本男鞋","人本女鞋","人本童鞋",
  "环球帆布鞋","环球男鞋","环球女鞋","环球童鞋",
  "鸿星尔克男鞋","鸿星尔克女鞋","鸿星尔克童鞋","鸿星尔克跑步鞋","鸿星尔克板鞋","鸿星尔克奇弹","鸿星尔克芷境","鸿星尔克儿童运动鞋",
  "乔丹中国男鞋","乔丹中国女鞋","乔丹中国童鞋","乔丹中国跑步鞋","乔丹中国篮球鞋","乔丹中国锋刺系列","乔丹中国磨砺系列","乔丹中国儿童鞋"
)
$json = $terms | ConvertTo-Json
[System.IO.File]::WriteAllText("e:\mynewproject2\custom-search-terms.json", $json, [System.Text.Encoding]::UTF8)
Write-Host "Done. Wrote $($terms.length) terms."
