@echo off
setlocal EnableDelayedExpansion
cd /d %~dp0
set NODE_ENV=development
set DATABASE_URL=postgresql://postgres:wpAxoWsjxiQfxCSnAnPdotRRMuDpOIdu@viaduct.proxy.rlwy.net:34644/railway
set GOOFISH_DATABASE_URL=postgresql://postgres:wpAxoWsjxiQfxCSnAnPdotRRMuDpOIdu@viaduct.proxy.rlwy.net:34644/railway
set GOOFISH_MUTATION_TIMEOUT_MS=15000
set GOOFISH_MUTATION_RETRY_COUNT=3
set GOOFISH_NEWOROLD_TIMEOUT_MS=8000
set GOOFISH_NEWOROLD_RETRY_COUNT=3
set GOOFISH_RETRY_BACKOFF_MS=500
set GOOFISH_PRODUCT_TIMEOUT_MS=120000
set GOOFISH_IMAGE_MUTATION_TIMEOUT_MS=10000
set GOOFISH_IMAGE_MUTATION_RETRY_COUNT=1
set GOOFISH_EMBEDDING_MUTATION_TIMEOUT_MS=8000
set GOOFISH_EMBEDDING_MUTATION_RETRY_COUNT=1
set GOOFISH_SPECS_MUTATION_TIMEOUT_MS=8000
set GOOFISH_SPECS_MUTATION_RETRY_COUNT=1
set GOOFISH_DB_SAVE_TIMEOUT_MS=10000
set GOOFISH_DB_SAVE_RETRIES=1
set GOOFISH_DB_SAVE_FATAL_ON_RETRY_EXHAUST=false
set GOOFISH_DB_SAVE_BACKOFF_MS=500
set GOOFISH_DB_CONNECT_TIMEOUT_MS=20000
set GOOFISH_DB_CONNECT_RETRIES=3
set GOOFISH_DB_CONNECT_RETRY_DELAY_MS=5000
set GOOFISH_DB_CONNECT_VERIFY_PING=true
set GOOFISH_DB_ENGINE_FAILURE_THRESHOLD=3
set GOOFISH_DB_ENGINE_FAILURE_WINDOW_MS=120000
set GOOFISH_DB_ENGINE_COOLDOWN_MS=45000
set GOOFISH_DB_FORCE_RECONNECT_MIN_INTERVAL_MS=45000
set GOOFISH_PROGRESS_STALL_TIMEOUT_MS=240000
set GOOFISH_PROGRESS_WATCHDOG_INTERVAL_MS=10000
set GOOFISH_PROGRESS_RECOVERY_COOLDOWN_MS=30000
set GOOFISH_PROGRESS_STALL_MAX_RECOVERS=3
set GOOFISH_PROGRESS_STALL_HARD_EXIT_MS=360000
set GOOFISH_PROCESS_LINK_TIMEOUT_MS=120000
set GOOFISH_DB_RECOVER_WAIT_MS=8000
set GOOFISH_DB_RECOVER_PING_TIMEOUT_MS=12000
set GOOFISH_DB_RECOVER_MAX_CYCLES_PER_OP=1
set GOOFISH_AI_CALL_TIMEOUT_MS=30000
set GOOFISH_AI_RETRY_MAX_ATTEMPTS=1
set GOOFISH_AI_MODEL=Qwen/Qwen3-8B
set GOOFISH_AI_SECOND_PASS_DESCRIPTION=true
set GOOFISH_ENABLE_TRANSLATION_RETRY=false
set GOOFISH_SKIP_ON_TRANSLATION_FAILURE=true
set GOOFISH_RESET_TERMS_ON_START=false
set GOOFISH_ITEMS_PER_SEARCH=90
set GOOFISH_LINKS_PER_TERM=90
set GOOFISH_TERMS_PER_BATCH=50
set GOOFISH_EMBED_USE_PRODUCT_NAME=true
set CLIP_WARMUP=true
set CLIP_MAX_IMAGE_SIDE=1024
set CLIP_ENABLE_RESIZE=false
set GOOFISH_PIPELINE_RESTART_DELAY_SEC=15
set GOOFISH_PIPELINE_RESTART_MAX_DELAY_SEC=60
set GOOFISH_PIPELINE_MAX_RESTARTS=0
set /a GOOFISH_PIPELINE_ATTEMPT=0
:pipeline_loop
set /a GOOFISH_PIPELINE_ATTEMPT+=1
echo.
echo Starting goofish pipeline attempt !GOOFISH_PIPELINE_ATTEMPT!...
node server/scripts/goofish-pipeline.js
set "GOOFISH_PIPELINE_EXIT=%ERRORLEVEL%"
if "%GOOFISH_PIPELINE_EXIT%"=="0" goto pipeline_done
if not "%GOOFISH_PIPELINE_MAX_RESTARTS%"=="0" if !GOOFISH_PIPELINE_ATTEMPT! GEQ %GOOFISH_PIPELINE_MAX_RESTARTS% goto pipeline_failed
echo.
set /a GOOFISH_PIPELINE_DELAY_SEC=%GOOFISH_PIPELINE_RESTART_DELAY_SEC% + ((!GOOFISH_PIPELINE_ATTEMPT!-1) * 5)
if !GOOFISH_PIPELINE_DELAY_SEC! GTR %GOOFISH_PIPELINE_RESTART_MAX_DELAY_SEC% set /a GOOFISH_PIPELINE_DELAY_SEC=%GOOFISH_PIPELINE_RESTART_MAX_DELAY_SEC%
echo Pipeline exited with code %GOOFISH_PIPELINE_EXIT%. Waiting !GOOFISH_PIPELINE_DELAY_SEC!s, then resuming from saved progress...
powershell -NoProfile -Command "Start-Sleep -Seconds !GOOFISH_PIPELINE_DELAY_SEC!"
goto pipeline_loop
:pipeline_failed
echo.
echo Pipeline failed after !GOOFISH_PIPELINE_ATTEMPT! attempts. Last exit code: %GOOFISH_PIPELINE_EXIT%
pause
exit /b %GOOFISH_PIPELINE_EXIT%
:pipeline_done
echo.
echo Pipeline finished successfully.
pause
